### ISSUE TITLE
Request: Add schematics

### ISSUE THREAD

**Issue by MarkusvonStaden** [AfterEarthLTD/Solder-Reflow-Plate#4]
First of all: Great Work! This is awesome!

I'd like to make a version with USB C. 
Could you upload the schematic in EasyEDA format? Currently the schematic is only available as PDF. (Or I am just dumb)
It would save quite some not not having to reverse draw the schematic.

**Comment by AfterEarthLTD** [comment]
Have a look in /BoardVersions/70mmby50mmVer2.4/BoardFiles/EasyEDA
There should be a .json that you can import?
Let me know if it works as I've never done an import/export of EasyEDA before

Good luck with the USB C version by the way!! I had planned to do one myself in a few months. Will be interested to see how you get on

**Comment by MarkusvonStaden** [comment]
I think this is only the PCB. At least I did not get any schematic out of it.

**Comment by AfterEarthLTD** [comment]
Righto, sorted it.
Downloading the project only gave me a Readme.txt file annoyingly. 
However, I have exported the schematic in .json form and uploaded under /BoardVersions/70mmby50mm/BoardFiles/EasyEDA
Have a look, you should see both Schematic and PCB there now 
Ta
