### ISSUE TITLE
Burning bootloader with Arduino gives me Device signature error

### ISSUE THREAD

**Issue by wsiffer** [AfterEarthLTD/Solder-Reflow-Plate#48]
I ordered these boards from JLCPCB pre-soldered with the 328p. I am trying to burn the bootloader with an arduino and have all the pins wired directly from the UNO iscp pins to the reflow ISCP pins. 

Has anyone else got this issue? 
here is an image: 
![image](https://user-images.githubusercontent.com/67080408/204859731-92e48645-8ccd-4448-9127-c2ddb7093181.png)

**Comment by JoeLutz11** [comment]
Yes Got the same issue but don't know how tho solve it

**Comment by Johaan1314** [comment]
I think you need a crystal oscillator if you are burning it for the first
time. Check out the video link in the main page.

**Comment by wsiffer** [comment]
I actually found a fix by making sure to wire properly. I did blow up a chip trying to give it a clock signal. I ordered 5 and successfully programmed the next 4 after I figured out the wiring
