### ISSUE TITLE
[Suggestion] Reduce number of different components

### ISSUE THREAD

**Issue by SR-71x2** [AfterEarthLTD/Solder-Reflow-Plate#6]
The Components 13 (R 3K) and 14 (R 1K) on the BOM only appear once in the schematics to form a voltage divider.
It doesn't seem that there will be much current over this voltage divider, so i'd suggest reproducing it with a 10K and 3x 10K resistors.

That way, all resistors in the project would be 10K's.
Less rails required for a pick&place machine and no way to misplace when manual soldering.

Same method would probaply be possible for some capacitors.
Many of them seem to be only for buffering&filtering purposes without needing to be an exact value.

**Comment by AfterEarthLTD** [comment]
Good point! I'll look to change that. Should make things a little easier and cheaper to make.
