### ISSUE TITLE
[Suggestion] Add 24-Pin-Connector for ATX-Power-Supply

### ISSUE THREAD

**Issue by SR-71x2** [AfterEarthLTD/Solder-Reflow-Plate#7]
An ATX-Power-Supply already has
- 12V with 10-15A
- 5V with proper filtering
- 3,3V with proper filtering
- An On/Off Switch
- Proper Cooling for high loads

It would be nice to power the whole project directly from a 24-Pin Mainboard Connector.
Just Plug in an old PC's PSU and not worry about Mains-Voltage or blowing your Lab Power-Supply with the load.

The Reflow plate could have a power switch, switching the PSU.

**Comment by AfterEarthLTD** [comment]
An interesting idea. I hadn't thought of that. I'd like to make a much larger version for bigger boards in the not too distant future. That will require much more power than the 60W that this already uses. Stay tuned for a bigger version as I will certainly implement some, if not all, of your suggestions.
