### ISSUE TITLE
FR4

### ISSUE THREAD

**Issue by Rudis1261** [AfterEarthLTD/Solder-Reflow-Plate#9]
Looking forward to making one of these myself, is it necessary to order a higher temp grade FR4? The price seems to shoot up when you do so 😱 

Would TG150-160 be ok?

![www pcbway com_orderonline aspx](https://user-images.githubusercontent.com/1902518/155940806-76b5a69b-82f2-4ceb-9dce-e0a0d9354c1d.png)

**Comment by BackLogers** [comment]
I have a similar question and doubts, JLCPCB only offers the TG130. What does the durability look like? Is the temperature of 170 degrees achievable without damaging the surface?

**Comment by narendok** [comment]
same i doubt, In india, pcbpower offer 130, 150, >170 option , should i go 170 or 130-140 is fine ?

**Comment by AfterEarthLTD** [comment]
Hi all,
All of the boards I have ordered and tested have been TG130. I wanted to make the boards as accessible and affordable as possible, hence staying away from exotic materials and aluminium. 
The boards are limited to 180 degrees and stay there for only a short time. During my testing they show no damage, especially with the black silkscreen. 
I imagine higher TG may last longer, but is not necessary. 

Hope that helps
Chris

**Comment by narendok** [comment]
Nice, Thank you so much for sharing such amazing work, I'm trying one for sure for my startup. God bless you.

**Comment by Rudis1261** [comment]
@AfterEarthLTD  Awesome thanks for confirming, I am happy with going the standard as well then :grimacing:
